#list2code config file
application: list2code
version: 1
runtime: python
api_version: 1

admin_console:
  pages:
  - name: Setup Templates
    url: /admin/


handlers:
- url: /admin/.*
  script: admin.py
  login: admin

- url: /content
  static_dir: content

- url: /.*
  script: main.py
  

